version: 2.0

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/java/Libs.kt" }}-{{ checksum "buildSrc/src/main/java/Version.kt" }}-{{ checksum "build.gradle" }}-{{ checksum "water-tracker/build.gradle" }}-{{ checksum "lib-common/build.gradle" }}

jobs:
  build:
    working_directory: ~/x-labs

    docker:
      - image: circleci/android:api-27-alpha

    environment:
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble Debug
          command: ./gradlew assembleDebug --profile
      - store_artifacts:
          path: water-tracker/build/outputs/
      - store_artifacts:
          path: build/reports/profile/

      - run:
          name: Android Lint
          command: ./gradlew lint
      - store_artifacts:
          path: water-tracker/build/reports/lint-results.html

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  version: 2
  build_and_lint:
    jobs:
      - build